-- CREATE TABLE IF NOT EXISTS papers (
--     id VARCHAR PRIMARY KEY,
--     submitter VARCHAR,
--     authors TEXT,
--     title TEXT,
--     comments TEXT,
--     journal_ref VARCHAR,
--     doi VARCHAR,
--     report_no VARCHAR,
--     categories TEXT,
--     license VARCHAR,
--     abstract TEXT,
--     update_date DATE,
--     authors_parsed TEXT[]
-- );
--
-- CREATE TABLE IF NOT EXISTS versions (
--     paper_id VARCHAR,
--     version VARCHAR,
--     created_at TIMESTAMP,
--     FOREIGN KEY (paper_id) REFERENCES papers (id)
-- );
